language: node_js
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
node_js:
  - 8.90
branches:
  only:
  - master
script:
  - docker build -t $DOCKER_IMAGE --build-arg azure_user="$AZURE_WA_USERNAME"  --build-arg azure_pwd="$AZURE_WA_PASSWORD"  --build-arg azure_site="$AZURE_WA_SITE" .
